project:
  type: website
  output-dir: "docs"

website:
  title: "Jingzhi Pu"
  google-analytics: "G-1W6X56QSLP"
  search: false

  sidebar:
    style: "docked"
    search: false
    logo: files/hlyb_poket_new_dark_mid.png
    contents:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: people.qmd
        text: People
      - href: news.qmd
        text: News
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: contact.qmd
        text: Contact
    - text: "---"
    - text: |
        <div class="sidebar-icons">
          <!-- ORCID -->
          <a href="https://orcid.org/0000-0002-3042-335X" target="_blank" title="ORCID">
            <img src="https://info.orcid.org/wp-content/uploads/2020/12/orcid_16x16.png"
                 alt="ORCID" style="height:22px; width:22px;">
          </a>

          <!-- Google Scholar -->
          <a href="https://scholar.google.com/citations?user=RlYang0AAAAJ&hl=en" target="_blank" title="Google Scholar">
            <img src="https://scholar.google.com/favicon.ico"
                 alt="Google Scholar" style="height:22px; width:22px;">
          </a>

          <!-- ResearchGate -->
          <a href="https://www.researchgate.net/profile/Jingzhi-Pu" target="_blank" title="ResearchGate">
            <img src="https://upload.wikimedia.org/wikipedia/commons/5/5e/ResearchGate_icon_SVG.svg"
                 alt="ResearchGate" style="height:22px; width:22px;">
          </a>

          <!-- GitHub -->
          <a href="https://github.com/pujingzhi" target="_blank" title="GitHub">
            <img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
                 alt="GitHub" style="height:22px; width:22px;">
          </a>
        </div>
        
  #page-navigation: true

  # Without this, the page footer will not display. It is removed in index.qmd
  # navbar:
  #  background: dark

  page-footer:
    center:
      - text: \[Made with Quarto\]
        href: https://quarto.org
      - text: \[Source\]
        href: https://github.com/pujingzhi/pujingzhi.github.io
      - text: \[License\]
        href: https://raw.githubusercontent.com/pujingzhi/pujingzhi.github.io/master/LICENSE

format:
  html:
    title-block-banner: true # Enable banner for title block 
    toc: false # Disable floating TOC
    css: styles.css
    theme:
      light: [simplex, custom.scss]
      dark: [cyborg, custom_dark.scss]
    fontsize: 0.8em
    linestretch: 1.4
    mainfont: "sans-serif"
    #toc: true
    toc-title: "<br><br><br>"
    link-external-newwindow: true # open hyperlink in a new window
    minimal: true
