project:
  type: website
  output-dir: "docs"

website:
  title: "Jingzhi Pu"
  google-analytics: "G-1W6X56QSLP"
  search: false

  sidebar:
    style: "docked"
    search: false
    logo: files/hlyb_poket_new_dark_mid.png
    contents:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: people.qmd
        text: People
      - href: news.qmd
        text: News
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: contact.qmd
        text: Contact
        
  #page-navigation: true

  # Without this, the page footer will not display. It is removed in index.qmd
  # navbar:
  #  background: dark

  page-footer:
    center:
      - text: \[Made with Quarto\]
        href: https://quarto.org
      - text: \[Source\]
        href: https://github.com/pujingzhi/pujingzhi.github.io
      - text: \[License\]
        href: https://raw.githubusercontent.com/alisiahkoohi/alisiahkoohi.github.io/master/LICENSE

format:
  html:
    title-block-banner: true # Enable banner for title block 
    toc: false # Disable floating TOC
    css: styles.css
    theme:
      light: [simplex, custom.scss]
      dark: [cyborg, custom_dark.scss]
    fontsize: 1.0em
    linestretch: 1.4
    mainfont: "sans-serif"
    #toc: true
    toc-title: "<br><br><br>"
    link-external-newwindow: false
    minimal: true
