name: Publish Quarto site

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          quarto-version: latest

      - uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: .            # path to your site
          render: true
          GITHUB_EMAIL: quarto-github-actions-publish@example.com
          GITHUB_USERNAME: Quarto GHA Workflow Runner
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
